name: Github Pages Deploy

on:
  push:
    branches:
      - 'master'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.9]

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install and build
        working-directory: ./
        run: npm install && MSYS2_ARG_CONV_EXCL="--base-href" npm run build -- --base-href="/naumen-test/" && cp dist/naumen-test/browser/index.html dist/naumen-test/browser/404.html

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.6.0
        with:
          folder: dist/naumen-test/browser
